Repository netlify/petsofnetlify, pull requests merged in 2021-11, with the labels that each got.

#56 Hello Melody 🐩
  src/_data/pets.json
  src/images/melody.jpg
Labels: type: feature

#57 Remove Bo from Pets of Netlify
  src/_data/pets.json
Labels: type: content

#59 feat: Scroll as smooth as you pet ✨
  src/_includes/style.css
Labels: enhancement, type: chore
